openapi: 3.0.3
info:
  title: Terra User Manager
  description: |
    Terra User Manager

  version: 0.0.1
paths:
  # Unauthenticated Paths
  /status:
    get:
      security: [ ]
      summary: Returns the operational status of the service
      operationId: serviceStatus
      tags: [ Public ]
      responses:
        '200':
          description: Service can process requests
        '500':
          description: |
            Service cannot process requests. That might be because dependent services are
            unavailable, or because there is a problem with the service itself.

  /version:
    get:
      security: [ ]
      summary: Returns the deployed version of the service
      operationId: serviceVersion
      tags: [ Public ]
      responses:
        '200':
          description: Version properties
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionProperties'

  # User profile management
  /api/profile:
    parameters:
      - $ref: '#/components/parameters/ProfilePath'
    get:
      summary: Retrieve a profile property.
      operationId: getUserProfile
      tags: [ Profile ]
      responses:
        '200':
          $ref: '#/components/responses/LookupResult'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '500':
          $ref: '#/components/responses/ServerError'
    put:
      summary: Set a profile property.
      operationId: setUserProfile
      tags: [ Profile ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnyObject'
      responses:
        '200':
          $ref: '#/components/responses/LookupResult'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    # Please keep alphabetized
    AnyObject:
      type: object
      required: [value]
      properties:
        value: {}

    ErrorReport:
      type: object
      required: [message, statusCode, causes]
      properties:
        message:
          type: string
        statusCode:
          type: integer
        causes:
          type: array
          items:
            type: string

    LookupPath:
      type: string
      description: Paths are specified in dot notation. For example, "user.name.first"

    VersionProperties:
      type: object
      required: [ gitTag, gitHash, github, build ]
      properties:
        gitTag:
          type: string
          description: Git tag of currently deployed app.
        gitHash:
          type: string
          description: Git hash of currently deployed app.
        github:
          type: string
          description: Github link to currently deployed commit.
        build:
          type: string
          description: Version of the currently deployed app declared in build.gradle. Client and server versions are linked.

  parameters:
    ProfilePath:
      name: path
      in: query
      description: Lookup path of a user profile property
      explode: false
      schema:
        $ref: '#/components/schemas/LookupPath'

  responses:
    # Keep alphabetized please
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

    Conflict:
      description: Request conflicts with current state
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

    LookupResult:
      description: Value of requested property
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AnyObject'

    PermissionDenied:
      description: Permission denied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

  securitySchemes:
    authorization:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            openid: open id authorization
            email: email authorization
            profile: profile authorization
    bearerAuth:
      type: http
      scheme: bearer

security:
  - authorization: [ openid, email, profile ]
  - bearerAuth: [ ]
