name: Build and Test

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths-ignore: [ '*.md' ]
  pull_request:
    # Branch settings require status checks before merging, so don't add paths-ignore.
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Gradle cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: v1-${{ runner.os }}-gradle-${{ github.ref }}-${{ github.sha }}
    - name: Gradle build service
      run: ./gradlew --build-cache :service:build -x test

    - name: Upload spotbugs results
      uses: github/codeql-action/upload-sarif@main
      with:
        sarif_file: service/build/reports/spotbugs/main.sarif

  unit-tests:
    needs: [ build ]
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports: [ "5432:5432" ]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: v1-${{ runner.os }}-gradle-${{ github.ref }}-${{ github.sha }}

    - name: Make sure Postgres is ready and init
      env:
        PGPASSWORD: postgres
      run: |
        pg_isready -h localhost -t 10
        psql -h localhost -U postgres -f ./scripts/local-postgres-init.sql

    - name: Run tests
      run: ./gradlew --build-cache :service:test --scan
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Reports
        path: ./service/build/reports/tests
    - name: Get current date
      id: date
      if: failure() && contains(github.actor, 'verily-automation-bot')
      run: echo date=$(TZ=America/New_York date +"%-m/%-d") >> $GITHUB_OUTPUT
